protected/models/Lhp.php
<?php

/**
 * This is the model class for table "lhp".
 *
 * The followings are the available columns in table 'lhp':
 * @property integer $id
 * @property string $nomor
 * @property string $kepada
 * @property string $dari
 * @property string $tanggal
 * @property string $hal
 * @property integer $id_spd
 * @property string $kesimpulan
 *
 * The followings are the available model relations:
 * @property Spd $idSpd
 */
class Lhp extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Lhp the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'lhp';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nomor, kepada, dari, hal, kesimpulan','required','message'=>'{attribute} tidak boleh kosong'),
			array('id_spd', 'numerical', 'integerOnly'=>true),
			array('nomor, kepada, dari, hal, kesimpulan', 'length', 'max'=>255),
			array('tanggal', 'safe'),
			array('nomor','nomorUnik'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, nomor, kepada, dari, tanggal, hal, id_spd, kesimpulan', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'spd' => array(self::BELONGS_TO, 'Spd', 'id_spd'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'nomor' => 'Nomor',
			'kepada' => 'Kepada',
			'dari' => 'Dari',
			'tanggal' => 'Tanggal',
			'hal' => 'Hal',
			'id_spd' => 'Nomor Spd',
			'kesimpulan' => 'Kesimpulan',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('nomor',$this->nomor,true);
		$criteria->compare('kepada',$this->kepada,true);
		$criteria->compare('dari',$this->dari,true);
		$criteria->compare('tanggal',$this->tanggal,true);
		$criteria->compare('hal',$this->hal,true);
		$criteria->compare('id_spd',$this->id_spd);
		$criteria->compare('kesimpulan',$this->kesimpulan,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'sort'=>array(
                    'defaultOrder'=>'id DESC',
                ),
		));
	}
	
	public function nomorUnik()
	{
		$model = Lhp::model()->findByAttributes(array('nomor'=>$this->nomor));
		if($model!==null)
		{
			if($model->id != $this->id)
				$this->addError('nomor','Ganti nomor LHP, sudah ada LHP yang menggunakan nomor tersebut');
			
		}
	}
	
	public function getRelationField($relation,$field)
	{
		if(!empty($this->$relation->$field))
			return $this->$relation->$field;
		else
			return null;
	}
	
	public function getRelationRelationField($relation1,$relation2,$field)
	{
		if(!empty($this->$relation1->$relation2->$field))
			return $this->$relation1->$relation2->$field;
		else
			return null;
	}
	
	public function getRelationRelationNip($relation1,$relation2)
	{
		if(!empty($this->$relation1->$relation2))
			return $this->$relation1->$relation2->getNip();
		else
			return null;
	}
}

protected/controllers/LhpController.php
<?php

class LhpController extends Controller
{
	/**
	* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	* using two-column layout. See 'protected/views/layouts/column2.php'.
	*/
	public $layout='//layouts/admin/column2';

	/**
	* @return array action filters
	*/
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'accessRole'
		);
	}

	/**
	* Specifies the access control rules.
	* This method is used by the 'accessControl' filter.
	* @return array access control rules
	*/
	
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('@'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('input','update','cetak','delete','cetakPdf'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','excel','exportExcel'),
				'users'=>array('@'),
			),		
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	* Displays a particular model.
	* @param integer $id the ID of the model to be displayed
	*/
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	* Creates a new model.
	* If creation is successful, the browser will be redirected to the 'view' page.
	*/
	public function actionInput()
	{
		$model=new Lhp;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Lhp']))
		{
			$model->attributes=$_POST['Lhp'];
			if($model->save())
			{
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('input'));
			}
		}

		$lhp=new Lhp('search');
		$lhp->unsetAttributes();  // clear any default values
		
		if(isset($_GET['Lhp']))
			$lhp->attributes=$_GET['Lhp'];

		$this->render('input',array(
			'model'=>$model,
			'lhp'=>$lhp
		));
	}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Lhp']))
		{
			$model->attributes=$_POST['Lhp'];
			if($model->save())
			{
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('input'));
			}
		}

		$lhp=new Lhp('search');
		$lhp->unsetAttributes();  // clear any default values
		
		if(isset($_GET['Lhp']))
			$lhp->attributes=$_GET['Lhp'];
		
		Yii::app()->user->setFlash('info','Silahkan sunting data pada kolom yang disediakan');
		
		$this->render('update',array(
			'model'=>$model,
			'lhp'=>$lhp,
		));
	}
	
	public function actionExcel()
	{
		$this->render('excel');
	}
	
	public function actionExportExcel()
	{
		$this->layout = '//layouts/excel';
		$this->render('_excel',array('border'=>1));
	}
	
	public function actionCetakPdf($id)
    {
	    $pdf=Yii::createComponent('application.extensions.tcpdf.ETcPdf', 'L', 'cm', 'A4', true, 'UTF-8');
		
		// create new PDF document
		$pdf = new TCPDF('P', PDF_UNIT, 'A3', true, 'UTF-8', false);
		// set document information
		$pdf->SetCreator(PDF_CREATOR);
		$pdf->SetAuthor('Surat Perjalanan Dinas');
		$pdf->SetTitle('Data Pegawai');
		$pdf->SetSubject('Data Pegawai');
		$pdf->setPrintHeader(false);
		$pdf->setPrintFooter(false);
		//$pdf->SetKeywords('TCPDF, PDF, example, test, guide');
		$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
		//$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
		//set auto page breaks
		$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
		// add a page
		$pdf->AddPage('P', 'Legal');
		$pdf->SetFont('times', '', 12);
		
		$model = $this->loadModel($id);
		
		$html = '';
		
		if(isset($_GET['kop']) AND $_GET['kop']=='setda') 
		{		
			$html .= ' 
				<table style="border-bottom:1px;">
					<tr>
						<td width="15%">
							<img src="'.Yii::app()->request->baseUrl.'/img/logo.jpg" width="65px">
						</td>
						<td width="85%">
							<p style="font-size:70px;line-height:100%;text-align:center">
							<b>PEMERINTAH KOTA SERANG</b><br>
							<b>SEKRETARIAT DAERAH</b><br>
							<i style="font-size:29px;">Jl. Jendral Sudirman Kawasan Perumahan Kota Serang Baru Telp.(0254)210538,FAX.(0254)202810</i></p>
						</td>
					</tr>
				</table>';
		}
		
		if(isset($_GET['kop']) AND $_GET['kop']=='dpkd') 
		{	
			$html=' <table style="border-bottom:1px;">
					<tr>
						<td width="15%">
							<img src="'.Yii::app()->request->baseUrl.'/img/logo.jpg" width="65px">
						</td>
						<td width="85%" >
							<p style="font-size:70px;line-height:93%;text-align:center" >
							<b>PEMERINTAH KOTA SERANG</b><br>
							<b style="font-size:50px;">DINAS PENGELOLAAN KEUANGAN DAERAH</b><br>
							( D P K D )<br>
							<i style="font-size:29px;">Jl. Jendral Sudirman Kawasan Perumahan Kota Serang Baru Telp.(0254)210538,FAX.(0254)202810</i></p>
						</td>
					</tr>
				</table>';
		}
		
		$html .= '
				<p style="text-align:center;font-weight:bold;font-size:42px;line-height:75%">N O T A &nbsp;&nbsp; D I N A S</p>
				
				<table>
					<tr>
						<td width="15%">
							Kepada
						</td>
						<td width="85%">
							: Yth. '.$model->kepada.'
						</td>
					</tr>
					<tr>
						<td width="15%">
							Dari
						</td>
						<td width="85%">
							: '.$model->dari.'
						</td>
					</tr>
					<tr>
						<td width="15%">
							Tanggal
						</td>
						<td width="85%">
							: '.Bantu::tanggal(date('Y-m-d')).'
						</td>
					</tr>
					<tr>
						<td width="15%">
							Hal
						</td>
						<td width="85%">
							: '.$model->hal.'
						</td>
					</tr>
					<tr>
						<td width="100%" style="border-bottom:0px solid #000">&nbsp;</td>
					</tr>
				</table>';
		
		$html .= '<p style="line-height:10%">&nbsp;</p>';
		
		$html .= '

				<table width="100%" celpadding="1px">
					<tr>
						<td width="3%"><b>1.</b></td>
						<td width="97%" colspan="2"><b>Dasar Hukum</b></td>
					</tr>
					<tr>
						<td width="3%">&nbsp;</td>
						<td width="30%">Surat Perintah</td>
						<td width="67%"> : '.$model->kepada.'</td>
					</tr>
					<tr>
						<td width="3%">&nbsp;</td>
						<td width="30%">Nomor</td>
						<td width="67%"> : '.$model->nomor.'</td>
					</tr>
					<tr>
						<td width="3%">&nbsp;</td>
						<td width="30%">Tanggal</td>
						<td width="57%"> : '.Bantu::tanggal(($model->tanggal)).'</td>
					</tr>
					<tr>
						<td width="3%">&nbsp;</td>
						<td width="30%">Memerintahkan kepada</td>
						<td width="67%"> : </td>
					</tr>
					<tr>
						<td width="3%">&nbsp;</td>
						<td width="40%">a) '.$model->getRelationRelationField("spd","pegawai","nama").'</td>
						<td width="57%">: '.$model->getRelationRelationField("spd","pegawai","jabatan").'</td>
					</tr>';
		$i = 98; 
		foreach(Pengikut::model()->findAllByAttributes(array('id_spd'=>$model->id_spd,'aktif'=>1)) as $pengikut)
		{
			$html .= '
				
					<tr>
						<td width="3%" align="center">&nbsp;</td>
						<td width="40%" >'.chr($i).') '.$pengikut->getRelationField("pegawai","nama").'</td>
						<td width="57%" >: '.$pengikut->getRelationField("pegawai","jabatan").'</td>
					</tr>';
			$i++;
		}				
		$html .= '
					<tr>
						<td width="100%" colspan="3">&nbsp;</td>
					</tr>
					<tr>
						<td width="3%"><b>2.</b></td>
						<td width="97%" colspan="2"><b>Maksud dan Tujuan</b></td>
					</tr>
					<tr>
						<td width="3%">&nbsp;</td>
						<td width="97%" colspan="2">'.$model->getRelationField("spd","maksud").'</td>
					</tr>
					<tr>
						<td width="100%" colspan="3">&nbsp;</td>
					</tr>
					<tr>
						<td width="3%"><b>3.</b></td>
						<td width="97%" colspan="2"><b>Kesimpulan / Rangkuman isi hasil perjalanan dinas</b></td>
					</tr>
					<tr>
						<td width="3%">&nbsp;</td>
						<td width="97%" colspan="2">'.$model->kesimpulan.'</td>
					</tr>
					<tr>
						<td width="100%" colspan="3">&nbsp;</td>
					</tr>
					<tr>
						<td width="100%" colspan="3">Demikian disampaikan atas perhatiannya diucapkan terimakasih</td>
					</tr>
				</table>';

		$html .= '
				<table>
					<tr>
						<td width="50%">&nbsp;</td>
						<td width="50%" align="center">
							<p>'.$model->getRelationRelationField("spd","pegawai","jabatan").'</p>
							<div>&nbsp;</div>
							<p style="line-height:100%"><b><u>'.$model->getRelationRelationField("spd","pegawai","nama").'</u></b>
							<br>NIP. '.$model->getRelationRelationNip("spd","pegawai").'</p>
						</td>
					</tr>
				</table>';
		
		$html .= '<div>&nbsp;</div>';

		if(!isset($_GET['nonPengikut']))
		{
			$html .='	
				<table>
					<tr>
						<td style="text-align:center"><b>Unsur Pengikut:</b></td>
					</tr>';
		
			foreach(Pengikut::model()->findAllByAttributes(array('id_spd'=>$model->id_spd,'aktif'=>1)) as $pengikut)
			{
				$html .='
					<tr>
						<td width="40%">&nbsp;<br>'.$pengikut->pegawai->nama.'</td>
						<td width="40%" style="border-bottom:0px solid #000">&nbsp;<br></td>
						<td width="20%">&nbsp;</td>
					</tr>';
			}
			
			$html .='</table>';
		
		}
		
		$pdf->writeHTML($html, true, true, true, true, '');

		//Close and output PDF document
		$pdf->Output('.pdf', 'I');	
 
    }

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))

protected/views/lhp/_admin.php
<?php $this->widget('bootstrap.widgets.TbGridView',array(
		'id'=>'lhp-grid',
		'type'=> 'striped bordered',
		'dataProvider'=>$lhp->search(),
		'filter'=>$lhp,
		'columns'=>array(
			array(
				'class'=>'CDataColumn',
				'type'=>'raw',
				'header'=>'Cetak',
				'value'=>'CHtml::link("<center><i class=icon-print ></i></center>",array("lhp/view","id"=>"$data->id"))',
			),
			'nomor',
			array(
				'class'=>'CDataColumn',
				'name'=>'id_spd',
				'header'=>'No. SPD',
				'type'=>'raw',
				'value'=>'$data->getRelationField("spd","nomor_spd")',
				'filter'=>CHtml::listData(Spd::model()->findAll(),'id','nomor')
			),
			'kepada',
			'dari',	
			array(
				'class'=>'CDataColumn',
				'name'=>'tanggal',
				'header'=>'Tanggal',
				'type'=>'raw',
				'value'=>'Yii::app()->dateFormatter->format("dd-MM-yyyy",$data->tanggal)',
			),
			'hal',
			'kesimpulan',
			array(
				'class'=>'bootstrap.widgets.TbButtonColumn',
				'template'=>'{update}{delete}'
			),
		),
)); ?>

protected/views/lhp/_excel.php
<table border="<?php print $border; ?>" class="table">
<tr>
	<th>NOMOR LHP</th>
	<th>TANGGAL</th>
	<th>KEPADA</th>
	<th>DARI</th>
	<th>NOMOR SPD</th>
	<th>HAL</th>
	<th>KESIMPULAN</th>
</tr>
<?php if(isset($_GET['tampil'])) { ?>
<?php
		$criteria = new CDbCriteria;
		$criteria->order = 'tanggal ASC';
		
		if(!empty($_GET['tanggal_awal']) AND !empty($_GET['tanggal_akhir']))
		{
			$criteria->condition = 'tanggal >= :tanggal_awal AND tanggal <= :tanggal_akhir';
			$criteria->params = array(':tanggal_awal'=>$_GET['tanggal_awal'],':tanggal_akhir'=>$_GET['tanggal_akhir']);
		}
?>

<?php $i=1; foreach(LHP::model()->findAll($criteria) as $data) { ?>
<tr>
	<td><?php print $data->nomor; ?></td>
	<td><?php print $data->tanggal; ?></td>
	<td><?php print $data->kepada; ?></td>
	<td><?php print $data->dari; ?></td>
	<td><?php print $data->getRelationField("spd","nomor_spd"); ?></td>
	<td><?php print $data->hal; ?></td>
	<td><?php print $data->kesimpulan; ?></td>
</tr>
<?php $i++; } ?>
<?php } ?>
</table>

protected/views/lhp/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'nomor',array('class'=>'span5','maxlength'=>255)); ?>

		<?php echo $form->textFieldRow($model,'kepada',array('class'=>'span5','maxlength'=>255)); ?>

		<?php echo $form->textFieldRow($model,'dari',array('class'=>'span5','maxlength'=>255)); ?>

		<?php echo $form->textFieldRow($model,'tanggal',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'hal',array('class'=>'span5','maxlength'=>255)); ?>

		<?php echo $form->textFieldRow($model,'id_spd',array('class'=>'span5')); ?>

		<?php echo $form->textFieldRow($model,'kesimpulan',array('class'=>'span5','maxlength'=>255)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/lhp/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nomor')); ?>:</b>
	<?php echo CHtml::encode($data->nomor); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('kepada')); ?>:</b>
	<?php echo CHtml::encode($data->kepada); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('dari')); ?>:</b>
	<?php echo CHtml::encode($data->dari); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('tanggal')); ?>:</b>
	<?php echo CHtml::encode($data->tanggal); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('hal')); ?>:</b>
	<?php echo CHtml::encode($data->hal); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('id_spd')); ?>:</b>
	<?php echo CHtml::encode($data->id_spd); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('kesimpulan')); ?>:</b>
	<?php echo CHtml::encode($data->kesimpulan); ?>
	<br />

	*/ ?>

</div>

protected/views/lhp/cetak.php
<?php
$this->breadcrumbs=array(
	'Lhps'=>array('index'),
	'Manage',
);

$this->menu=array(
array('label'=>'List Lhp','url'=>array('index')),
array('label'=>'Create Lhp','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('lhp-grid', {
data: $(this).serialize()
});
return false;
});
");
?>

<h1>Cetak Laporan Hasil Perjalanan Dinas</h1>

<div>Silahkan klik simbol printer <i class="icon-print"></i> untuk memilih data yang akan dicetak</div>

<?php $this->renderPartial('_admin',array('lhp'=>$model)); ?>

protected/views/lhp/index.php
<?php
$this->breadcrumbs=array(
	'Lhps',
);

$this->menu=array(
array('label'=>'Create Lhp','url'=>array('create')),
array('label'=>'Manage Lhp','url'=>array('admin')),
);
?>

<h1>Lhps</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/lhp/input.php
<?php
$this->breadcrumbs=array(
	'Lhps'=>array('index'),
	'Create',
);

$this->menu=array(
array('label'=>'List Lhp','url'=>array('index')),
array('label'=>'Manage Lhp','url'=>array('admin')),
);
?>

<h1>Laporan Hasil Perjalanan Dinas</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

<?php echo $this->renderPartial('_admin', array('lhp'=>$lhp)); ?>

protected/views/lhp/update.php
<?php
$this->breadcrumbs=array(
	'Lhps'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

	$this->menu=array(
	array('label'=>'List Lhp','url'=>array('index')),
	array('label'=>'Create Lhp','url'=>array('create')),
	array('label'=>'View Lhp','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Lhp','url'=>array('admin')),
	);
	?>
<h1>Laporan Hasil Perjalanan Dinas</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

<?php print $this->renderPartial('_admin', array('lhp'=>$lhp)); ?>

protected/views/lhp/view.php
<?php
$this->breadcrumbs=array(
	'Lhps'=>array('index'),
	$model->id,
);

$this->menu=array(
array('label'=>'List Lhp','url'=>array('index')),
array('label'=>'Create Lhp','url'=>array('create')),
array('label'=>'Update Lhp','url'=>array('update','id'=>$model->id)),
array('label'=>'Delete Lhp','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage Lhp','url'=>array('admin')),
);
?>

<h1>Detail LHP</h1>

<?php $this->widget('bootstrap.widgets.TbButton',array(
		'label' => 'LHP kop SETDA',
		'icon'=>'download-alt white',
		'type' => 'primary',
		'url'=>array('lhp/cetakPdf','id'=>$model->id,'kop'=>'setda'),
		'htmlOptions'=>array('target'=>'_blank')
)); ?> 

<?php $this->widget('bootstrap.widgets.TbButton',array(
		'label' => 'LHP kop SETDA Non Pengikut',
		'icon'=>'download-alt white',
		'type' => 'primary',
		'url'=>array('lhp/cetakPdf','id'=>$model->id,'kop'=>'setda','nonPengikut'=>1),
		'htmlOptions'=>array('target'=>'_blank')
)); ?> 

<?php $this->widget('bootstrap.widgets.TbButton',array(
		'label' => 'LHP kop DPKD',
		'icon'=>'download-alt white',
		'type' => 'primary',
		'url'=>array('lhp/cetakPdf','id'=>$model->id,'kop'=>'dpkd'),
		'htmlOptions'=>array('target'=>'_blank')
)); ?>

<?php $this->widget('bootstrap.widgets.TbButton',array(
		'label' => 'LHP kop DPKD Non Pengikut',
		'icon'=>'download-alt white',
		'type' => 'primary',
		'url'=>array('lhp/cetakPdf','id'=>$model->id,'kop'=>'dpkd','nonPengikut'=>1),
		'htmlOptions'=>array('target'=>'_blank')
)); ?>

<div>&nbsp;</div>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
		'data'=>$model,
		'type'=>'striped bordered',
		'attributes'=>array(
			'nomor',
			array(
				'label'=>'No. SPD',
				'value'=>$model->getRelationField('spd','nomor_spd')
			),
			'kepada',
			'dari',
			'tanggal',
			'hal',
			'kesimpulan',
		),
)); ?>

<?php $this->widget('bootstrap.widgets.TbButton',array(
		'label' => 'Input LHP',
		'icon'=>'plus white',
		'type' => 'primary',
		'url'=>array('lhp/create'),
)); ?>

<?php $this->widget('bootstrap.widgets.TbButton',array(
		'label' => 'Sunting LHP',
		'icon'=>'pencil white',
		'type' => 'primary',
		'url'=>array('lhp/update','id'=>$model->id),
)); ?>