protected/models/Kwitansi.php
<?php

/**
 * This is the model class for table "kwitansi".
 *
 * The followings are the available columns in table 'kwitansi':
 * @property integer $id
 * @property string $nomor
 * @property integer $id_spd
 * @property integer $id_akomodasi
 * @property integer $id_refresentatif
 * @property integer $id_ssh
 * @property integer $bendahara
 * @property integer $ppk
 * @property string $bbm
 * @property string $tol
 * @property string $tiket
 * @property string $total
 *
 * The followings are the available model relations:
 * @property Akomodasi $idAkomodasi
 * @property Pejabat $bendahara0
 * @property Pejabat $ppk0
 * @property Refresentatif $idRefresentatif
 * @property Spd $idSpd
 * @property Ssh $idSsh
 */
class Kwitansi extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Kwitansi the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'kwitansi';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('id_spd, lama, penerima, bendahara, pptk, pa', 'numerical', 'integerOnly'=>true),
			array('nomor,spd,akomodasi,uang_harian, bendahara, pptk, pa, penerima','required','message'=>'{attribute} tidak boleh kosong'),
			array('nomor, bbm, tol, tiket, total, akomodasi, refresentatif, uang_harian,', 'length', 'max'=>255),
			array('tanggal','safe'),
			array('nomor','nomorUnik'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, nomor, id_spd, id_akomodasi, id_refresentatif, id_ssh, bendahara, ppk, bbm, tol, tiket, total', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'penerimaRelation' => array(self::BELONGS_TO, 'Pegawai', 'penerima'),
			'akomodasi' => array(self::BELONGS_TO, 'Akomodasi', 'id_akomodasi'),
			'bendaharaRelation' => array(self::BELONGS_TO, 'Pejabat', 'bendahara'),
			'pptkRelation' => array(self::BELONGS_TO, 'Pejabat', 'pptk'),
			'paRelation' => array(self::BELONGS_TO, 'Pejabat', 'pa'),
			'refresentatif' => array(self::BELONGS_TO, 'Refresentatif', 'id_refresentatif'),
			'spd' => array(self::BELONGS_TO, 'Spd', 'id_spd'),
			'ssh' => array(self::BELONGS_TO, 'Ssh', 'id_ssh'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'nomor' => 'Nomor Kwitansi',
			'id_spd' => 'Nomor SPD',
			'id_akomodasi' => 'Akomodasi',
			'id_refresentatif' => 'Refresentatif',
			'id_ssh' => 'Uang Harian',
			'bendahara' => 'Bendahara',
			'pptk' => 'Pejabat Pelaksana Teknis Kegiatan',
			'pa'=>'PA/KPA',
			'bbm' => 'BBM',
			'tol' => 'Tol',
			'tiket' => 'Tiket',
			'total' => 'Total',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('nomor',$this->nomor,true);
		$criteria->compare('id_spd',$this->id_spd);
		$criteria->compare('penerima',$this->penerima);
		$criteria->compare('akomodasi',$this->akomodasi);
		$criteria->compare('refresentatif',$this->refresentatif);
		$criteria->compare('uang_harian',$this->uang_harian);
		$criteria->compare('bendahara',$this->bendahara);
		$criteria->compare('pptk',$this->pptk);
		$criteria->compare('bbm',$this->bbm,true);
		$criteria->compare('tol',$this->tol,true);
		$criteria->compare('tiket',$this->tiket,true);
		$criteria->compare('total',$this->total,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'sort'=>array(
                    'defaultOrder'=>'id DESC',
                ),
		));
	}
	
	public function nomorUnik()
	{
		$model = Kwitansi::model()->findByAttributes(array('nomor'=>$this->nomor));
		if($model!==null)
		{
			if($model->id != $this->id)
				$this->addError('nomor','Ganti nomor kwitansi, sudah ada kwitansi yang menggunakan nomor tersebut');
			
		}
	}
	
	public function getRelationField($relation,$field)
	{
		if(!empty($this->$relation->$field))
			return $this->$relation->$field;
		else
			return null;
	}
	
	public function getRelationNip($relation)
	{
		if(!empty($this->$relation))
			return $this->$relation->getNip();
		else
			return null;
	}
	
}

protected/controllers/KwitansiController.php
<?php

class KwitansiController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/admin/column2';

/**
* @return array action filters
*/
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'accessRole'
		);
	}

	/**
	* Specifies the access control rules.
	* This method is used by the 'accessControl' filter.
	* @return array access control rules
	*/
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','delete'),
				'users'=>array('@'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('input','update','cetak','cetakPdf','excel','exportExcel','cetakPdfMpdf'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	* Creates a new model.
	* If creation is successful, the browser will be redirected to the 'view' page.
	*/
	public function actionInput()
	{
		$model=new Kwitansi;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kwitansi']))
		{
			$model->attributes=$_POST['Kwitansi'];
			
			$model->uang_harian = str_replace('.','',$model->uang_harian);
			$model->akomodasi = str_replace('.','',$model->akomodasi);
			$model->refresentatif = str_replace('.','',$model->refresentatif);
			$model->bbm = str_replace('.','',$model->bbm);
			$model->tol = str_replace('.','',$model->tol);
			$model->tiket = str_replace('.','',$model->tiket);
			
			$model->total = 0;
			$model->total += floatval($model->uang_harian);
			$model->total += floatval($model->akomodasi);
			$model->total += floatval($model->refresentatif);
			$model->total += floatval($model->bbm);
			$model->total += floatval($model->tol);
			$model->total += floatval($model->tiket);
			
			if($model->save())
			{
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('input'));
			}
		}

		$kwitansi = new Kwitansi('search');
		$kwitansi->unsetAttributes();  // clear any default values
		
		if(isset($_GET['Kwitansi']))
			$kwitansi->attributes=$_GET['Kwitansi'];

			
		$akomodasi = new Akomodasi;
		$refresentatif = new Refresentatif;
		$uangHarian = new UangHarian;
		
		$this->render('input',array(
			'model'=>$model,
			'kwitansi'=>$kwitansi,
			'akomodasi'=>$akomodasi,
			'refresentatif'=>$refresentatif,
			'uangHarian'=>$uangHarian
		));
	}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kwitansi']))
		{
			$model->attributes=$_POST['Kwitansi'];
			
			$model->uang_harian = str_replace('.','',$model->uang_harian);
			$model->akomodasi = str_replace('.','',$model->akomodasi);
			$model->refresentatif = str_replace('.','',$model->refresentatif);
			$model->bbm = str_replace('.','',$model->bbm);
			$model->tol = str_replace('.','',$model->tol);
			$model->tiket = str_replace('.','',$model->tiket);
			
			$model->total = 0;
			$model->total += floatval($model->uang_harian*$model->spd->lama);
			$model->total += floatval($model->akomodasi);
			$model->total += floatval($model->refresentatif);
			$model->total += floatval($model->bbm);
			$model->total += floatval($model->tol);
			$model->total += floatval($model->tiket);
			
			if($model->save())
			{	
				Yii::app()->user->setFlash('success','Data berhasil disimpan');
				$this->redirect(array('input'));
			}
		}

		$kwitansi=new Kwitansi('search');
		$kwitansi->unsetAttributes();  // clear any default values
			
		if(isset($_GET['Kwitansi']))
			$kwitansi->attributes=$_GET['Kwitansi'];

		Yii::app()->user->setFlash('info','Silahkan sunting data pada kolom yang disediakan');
		
		$akomodasi = new Akomodasi;
		$refresentatif = new Refresentatif;
		$uangHarian = new UangHarian;
		
		$this->render('update',array(
			'model'=>$model,
			'kwitansi'=>$kwitansi,
			'akomodasi'=>$akomodasi,
			'refresentatif'=>$refresentatif,
			'uangHarian'=>$uangHarian
		));
	}
	
	public function actionExcel()
	{
		$this->render('excel');
	}
	
	public function actionExportExcel()
	{
		$this->layout = '//layouts/excel';
		$this->render('_excel',array('border'=>1));
	}
	
	public function actionCetakPdf($id)
    {
	    $pdf=Yii::createComponent('application.extensions.tcpdf.ETcPdf', 'L', 'cm', 'A3', true, 'UTF-8');
		// create new PDF document
		$pdf = new TCPDF('P', PDF_UNIT, 'F4', true, 'UTF-8', false);
		// set document information
		$pdf->SetCreator(PDF_CREATOR);
		$pdf->SetAuthor('RINCIAN BIAYA PERJALANAN DINAS');
		$pdf->SetTitle('RINCIAN BIAYA PERJALANAN DINAS');
		$pdf->SetSubject('RINCIAN BIAYA PERJALANAN DINAS');
		$pdf->setPrintHeader(false);
		$pdf->setPrintFooter(false);
		//$pdf->SetKeywords('TCPDF, PDF, example, test, guide');
		$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
		//$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
		
		//set auto page breaks
		$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
		// add a page
		$pdf->AddPage( 'P', 'F4');
		$pdf->SetFont('times', '', 8);
		
		
		$model = $this->loadModel($id);
		
		$html='
				<div style="line-height:100%;text-align:right"><i>Lampiran VII<br>Permenkeu RI. no.113 /PMK 05/2012</i></div>
				<div style="text-align:center;line-height:50%"><b><u>RINCIAN BIAYA PERJALANAN DINAS</u></b></div>';
		
		$html .= '<br>';
		
		$tanggal_spd = $model->getRelationField("spd","tanggal_spt");
		
		if($model->getRelationField("spd","tanggal_spd")!=null)
		{
			$tanggal_spd = $model->getRelationField("spd","tanggal_spd");
		}

		$html .= '
			    <table width="100%">
					<tr>
			    		<td width="25%">Lampiran SPPD Nomor</td>
			    		<td width="75%">: '.$model->getRelationField("spd","nomor_spd").'</td>
			    	</tr>
			    	<tr>
			    		<td width="25%">Tanggal</td>
			    		<td width="75%">: '.Bantu::tanggal($tanggal_spd).'</td>
			    	</tr>
			    </table>';
		
		$html .= '	    
			    <table border="0px;" cellpadding="1px">
			    	<tr>
			    		<td width="7%" style="text-align:center;font-weight:bold;border-top:0px solid #000;border-bottom:0px solid #000;border-left:0px solid #000">NO</td>
			    		<td width="36%" style="text-align:center;font-weight:bold;border-top:0px solid #000;border-bottom:0px solid #000;border-left:0px solid #000">Perincian Biaya</td>
			    		<td width="26%" style="text-align:center;font-weight:bold;border-top:0px solid #000;border-bottom:0px solid #000;border-left:0px solid #000">Jumlah</td>
			    		<td width="31%" style="text-align:center;font-weight:bold;border-top:0px solid #000;border-bottom:0px solid #000;border-left:0px solid #000;border-right:0px solid #000">Keterangan</td>
			    	</tr>
			    	';
		
		$i = 1;
		
		$total = 0;
		
		if(isset($_GET['dalamDaerah']) AND $_GET['dalamDaerah']==1)
		{
		
			$html .='
			    	<tr>
			    		<td width="7%" style="text-align:center;border-left:0px solid #000">
			    			'.$i.'
			    		</td>
			    		<td width="36%" style="border-left:0px solid #000">
			    			Uang Harian
			    		</td>
			    		<td width="26%" style="border-left:0px solid #000;text-align:right">
			    			Rp '.number_format($model->uang_harian*$model->getRelationField("spd","lama"), 2,",",".").'
			    		</td>
			    		<td width="31%" style="border-left:0px solid #000;border-right:0px solid #000">'.$model->getRelationField("spd","maksud").'</td>
			    	</tr>';
			$i++; $total = $total + $model->uang_harian*$model->getRelationField("spd","lama");
			
		}
		
		if(isset($_GET['luarDaerah']) AND $_GET['luarDaerah']==1)
		{
			$html .='
			    	<tr>
			    		<td width="7%" style="text-align:center;border-left:0px solid #000;line-height:75%">
			    			'.$i.'.
			    		</td>
			    		<td width="36%" style="border-left:0px solid #000;line-height:75%">
			    			Biaya Transport
			    		</td>
			    		<td width="26%" style="border-left:0px solid #000;text-align:right;line-height:75%">&nbsp;
			    			
			    		</td>
			    		<td width="31%" style="border-left:0px solid #000;border-right:0px solid #000;line-height:75%">&nbsp;'.$model->spd->maksud.'</td>
			    	</tr>';
					
			$i++;
			
			$html .='
			    	<tr>
			    		<td width="7%" style="text-align:center;border-left:0px solid #000;line-height:75%">&nbsp;
			    			
			    		</td>
			    		<td width="36%" style="border-left:0px solid #000;line-height:75%"> 
							&nbsp;&nbsp;&nbsp;BBM
			    		</td>
			    		<td width="26%" style="border-left:0px solid #000;text-align:right;line-height:75%">
			    			Rp '.number_format($model->bbm, 2,",",".").'
			    		</td>
			    		<td width="31%" style="border-left:0px solid #000;border-right:0px solid #000;line-height:75%">&nbsp;
							
						</td>
			    	</tr>';
			
			$total = $total + $model->bbm;
					
			$html .='
			    	<tr>
			    		<td width="7%" style="text-align:center;border-left:0px solid #000;line-height:75%">&nbsp;
			    			
			    		</td>
			    		<td width="36%" style="border-left:0px solid #000;line-height:75%">
			    			&nbsp;&nbsp;&nbsp;TOL
			    		</td>
			    		<td width="26%" style="border-left:0px solid #000;text-align:right;line-height:75%">
			    			Rp '.number_format($model->tol, 2,",",".").'
			    		</td>
			    		<td width="31%" style="border-left:0px solid #000;border-right:0px solid #000;line-height:75%">&nbsp;
							
						</td>

protected/views/kwitansi/_admin.php
<?php $this->widget('bootstrap.widgets.TbGridView',array(
		'id'=>'kwitansi-grid',
		'type'=>'striped bordered',
		'dataProvider'=>$kwitansi->search(),
		'filter'=>$kwitansi,
		'columns'=>array(
			array(
				'class'=>'CDataColumn',
				'type'=>'raw',
				'header'=>'Cetak',
				'value'=>'CHtml::link("<center><i class=icon-print ></i></center>",array("kwitansi/view","id"=>"$data->id"))',
			),
			'nomor',
			array(
				'class'=>'CDataColumn',
				'name'=>'id_spd',
				'header'=>'No. SPD',
				'type'=>'raw',
				'value'=>'$data->getRelationField("spd","nomor_spd")',
				'filter'=>CHtml::listData(Spd::model()->findAll(),'id','nomor_spd')
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'penerima',
				'header'=>'Penerima',
				'type'=>'raw',
				'value'=>'$data->getRelationField("penerimaRelation","nama")',
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'uang_harian',
				'header'=>'Uang Harian',
				'type'=>'raw',
				'value'=>'number_format($data->uang_harian, 0,",",".")',
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'id_spd',
				'header'=>'Lama',
				'type'=>'raw',
				'value'=>'$data->getRelationField("spd","lama")',
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'uang_harian',
				'header'=>'Total Uang Harian',
				'type'=>'raw',
				'value'=>'number_format($data->uang_harian*$data->getRelationField("spd","lama"), 0,",",".")',
			),
			
			array(
				'class'=>'CDataColumn',
				'name'=>'akomodasi',
				'header'=>'Akomodasi',
				'type'=>'raw',
				'value'=>'number_format($data->akomodasi, 0,",",".")',
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'refresentatif',
				'header'=>'Refresentatif',
				'type'=>'raw',
				'value'=>'number_format($data->refresentatif, 0,",",".")',
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'tol',
				'header'=>'Tol',
				'type'=>'raw',
				'value'=>'number_format($data->tol, 0,",",".")',
			),
			array(
				'class'=>'CDataColumn',
				'name'=>'tiket',
				'header'=>'Tiket',
				'type'=>'raw',
				'value'=>'number_format($data->tiket, 0,",",".")',
			),
			
			array(
				'class'=>'CDataColumn',
				'name'=>'total',
				'header'=>'Total',
				'type'=>'raw',
				'value'=>'number_format($data->total, 0,",",".")',
			),
			
			array(
				'class'=>'bootstrap.widgets.TbButtonColumn',
				'template'=>'{update}{delete}',
				'htmlOptions'=>array('style'=>'width:50px')
			)
			
		),
)); ?>
	

protected/views/kwitansi/cetak.php
<?php
$this->breadcrumbs=array(
	'Kwitansis'=>array('index'),
	'Manage',
);

$this->menu=array(
array('label'=>'List Kwitansi','url'=>array('index')),
array('label'=>'Create Kwitansi','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('kwitansi-grid', {
data: $(this).serialize()
});
return false;
});
");
?>

<h1>Cetak Tanda Bukti Pembayaran</h1>

<div>Silahkan klik simbol printer <i class="icon-print"></i> untuk memilih data yang akan dicetak</div>

<?php print $this->renderPartial('_admin',array('kwitansi'=>$model)); ?>

protected/views/kwitansi/index.php
<?php
$this->breadcrumbs=array(
	'Kwitansis',
);

$this->menu=array(
array('label'=>'Create Kwitansi','url'=>array('create')),
array('label'=>'Manage Kwitansi','url'=>array('admin')),
);
?>

<h1>Kwitansis</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/kwitansi/view.php
<?php
$this->breadcrumbs=array(
	'Kwitansis'=>array('index'),
	$model->id,
);

$this->menu=array(
array('label'=>'List Kwitansi','url'=>array('index')),
array('label'=>'Create Kwitansi','url'=>array('create')),
array('label'=>'Update Kwitansi','url'=>array('update','id'=>$model->id)),
array('label'=>'Delete Kwitansi','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage Kwitansi','url'=>array('admin')),
);
?>

<h1>Cetak Kwitansi</h1>

<div>Silahkan pilih jenis kwitansi yang akan dicetak pada sisi kiri laman</div>

<?php print Bantu::getTerbilang("921000",0); ?>

<div>&nbsp;</div>

<div class="row-fluid">
	<div class="span3">
		<?php $this->widget('bootstrap.widgets.TbButton',array(
				'label' => 'Kwitansi Dalam Daerah',
				'icon'=>'download-alt white',
				'type' => 'primary',
				'url'=>array('kwitansi/cetakPdf','id'=>$model->id,'dalamDaerah'=>1),
				'htmlOptions'=>array('target'=>'_blank','style'=>'margin-bottom:2px')
		)); ?>

		<?php $this->widget('bootstrap.widgets.TbButton',array(
				'label' => 'Kwitansi Luar Daerah',
				'icon'=>'download-alt white',
				'type' => 'primary',
				'url'=>array('kwitansi/cetakPdf','id'=>$model->id,'luarDaerah'=>1),
				'htmlOptions'=>array('target'=>'_blank')
		)); ?>

		<div>&nbsp;</div>

		<?php $this->widget('bootstrap.widgets.TbButton',array(
				'label' => 'Kwitansi Dalam Daerah Non PPTK',
				'icon'=>'download-alt white',
				'type' => 'primary',
				'url'=>array('kwitansi/cetakPdf','id'=>$model->id,'dalamDaerah'=>1,'refresentatif'=>1,'nonPptk'=>1),
				'htmlOptions'=>array('target'=>'_blank','style'=>'margin-bottom:2px')
		)); ?>
			
		<?php $this->widget('bootstrap.widgets.TbButton',array(
				'label' => 'Kwitansi Luar Daerah Non PPTK',
				'icon'=>'download-alt white',
				'type' => 'primary',
				'url'=>array('kwitansi/cetakPdf','id'=>$model->id,'luarDaerah'=>1,'nonPptk'=>1),
				'htmlOptions'=>array('target'=>'_blank')
		)); ?>
		
		<div>&nbsp;</div>

		<?php $this->widget('bootstrap.widgets.TbButton',array(
				'label' => 'Kwitansi Dalam Daerah Refresentatif',
				'icon'=>'download-alt white',
				'type' => 'primary',
				'url'=>array('kwitansi/cetakPdf','id'=>$model->id,'dalamDaerah'=>1,'refresentatif'=>1),
				'htmlOptions'=>array('target'=>'_blank','style'=>'margin-bottom:2px')
		)); ?>
			
		<?php $this->widget('bootstrap.widgets.TbButton',array(
				'label' => 'Kwitansi Luar Daerah Refresentatif',
				'icon'=>'download-alt white',
				'type' => 'primary',
				'url'=>array('kwitansi/cetakPdf','id'=>$model->id,'luarDaerah'=>1,'refresentatif'=>1),
				'htmlOptions'=>array('target'=>'_blank')
		)); ?>
		
		<div>&nbsp;</div>
		
		<?php /*
		<?php $this->widget('bootstrap.widgets.TbButton',array(
				'label' => 'Register No Bukti',
				'icon'=>'download-alt white',
				'type' => 'primary',
				'url'=>array('export/ExportKwitansi','id'=>$model->id),
				'htmlOptions'=>array('target'=>'_blank','style'=>'margin-bottom:2px')
		)); ?>
		
		<?php $this->widget('bootstrap.widgets.TbButton',array(
				'label' => 'Rekap Detail Bukti',
				'icon'=>'download-alt white',
				'type' => 'primary',
				'url'=>array('export/ExportKwitansiDetail','id'=>$model->id),
				'htmlOptions'=>array('target'=>'_blank')
		)); ?>
		*/ ?>
	</div>
	<div class="span9">	
			<?php $this->widget('bootstrap.widgets.TbDetailView',array(
					'data'=>$model,
					'type'=>'striped bordered',
					'attributes'=>array(
						'nomor',
						array(
							'label'=>'Nomor SPD',
							'type'=>'raw',
							'value'=>CHtml::encode($model->getRelationField("spd","nomor_spd"))
						),
						array(
							'label'=>'Akomodasi',
							'type'=>'raw',
							'value'=>'Rp '.number_format($model->akomodasi, 2,",",".")
						),
						array(
							'label'=>'Refresentatif',
							'type'=>'raw',
							'value'=>'Rp '.number_format($model->refresentatif, 2,",",".")
						),
						array(
							'label'=>'Uang Harian',
							'type'=>'raw',
							'value'=>'Rp '.number_format($model->uang_harian, 2,",",".")
						),
						array(
							'label'=>'Bendahara',
							'type'=>'raw',
							'value'=>$model->getRelationField("bendaharaRelation","nama")
						),
						array(
							'label'=>'PPTK',
							'type'=>'raw',
							'value'=>$model->getRelationField("pptkRelation","nama")
						),
						array(
							'label'=>'PA/KPA',
							'type'=>'raw',
							'value'=>$model->getRelationField("paRelation","nama")
						),
						array(
							'label'=>'BBM',
							'type'=>'raw',
							'value'=>'Rp '.number_format($model->bbm, 2,",",".")
						),
						array(
							'label'=>'Tol',
							'type'=>'raw',
							'value'=>'Rp '.number_format($model->tol, 2,",",".")
						),
						array(
							'label'=>'Tiket',
							'type'=>'raw',
							'value'=>'Rp '.number_format($model->tiket, 2,",",".")
						),
						array(
							'label'=>'Total',
							'type'=>'raw',
							'value'=>'Rp <b>'.number_format($model->total, 2,",",".").'</b>'
						),
					),
			)); ?>
			
			<?php $this->widget('bootstrap.widgets.TbButton',array('buttonType'=>'link','type'=>'primary','label'=>'Sunting Kwitansi','icon'=>'pencil white','url'=>array('kwitansi/update','id'=>$model->id))); ?>

	</div>
</div>


<div>&nbsp;</div>